### Create a new check
POST https://exam.kode4u.tech/api/checks
Authorization: Bearer 14|BGgmzkcxXucOnuWZTAUc7imfR4tCVkJBzOLqEBBjebe90790
Content-Type: application/json

{
    "student_id": 1,
    "user_id": 1,
    "category_id": 1
}



### List all checks
GET https://exam.kode4u.tech/api/checks
Authorization: Bearer 14|BGgmzkcxXucOnuWZTAUc7imfR4tCVkJBzOLqEBBjebe90790

### Show a specific check
GET https://exam.kode4u.tech/api/checks/1
Authorization: Bearer 14|BGgmzkcxXucOnuWZTAUc7imfR4tCVkJBzOLqEBBjebe90790

### Update a check
PUT https://exam.kode4u.tech/api/checks/1
Authorization: Bearer 14|BGgmzkcxXucOnuWZTAUc7imfR4tCVkJBzOLqEBBjebe90790
Content-Type: application/json

{
    "student_id": 1,
    "user_id": 1,
    "category_id": 1
}

### Delete a check
DELETE https://exam.kode4u.tech/api/checks/1
Authorization: Bearer 14|BGgmzkcxXucOnuWZTAUc7imfR4tCVkJBzOLqEBBjebe90790
