### Get All CheckTables
GET https://exam.kode4u.tech/api/checks
Content-Type: application/json
Authorization: Bearer 25|fjutqBPclU6ACj9GucYm1a1SSrobquNRrsLDKt4l9d67215e

###

### Get CheckTables by Category ID
GET https://exam.kode4u.tech/api/checks?category_id=1
Content-Type: application/json

###

### Create a New CheckTable Entry
POST https://exam.kode4u.tech/api/checks
Content-Type: application/json

{
  "user_id": 1,
  "category_id": 1,
  "student_id": 1,
  "correct": true
}

###

### Get a Specific CheckTable Entry
GET https://exam.kode4u.tech/api/checks/1
Content-Type: application/json

###

### Update a CheckTable Entry
PUT https://exam.kode4u.tech/api/checks/1
Content-Type: application/json

{
  "user_id": 1,
  "category_id": 1,
  "student_id": 1,
  "correct": false
}

###

### Delete a CheckTable Entry
DELETE https://exam.kode4u.tech/api/checks/1
Content-Type: application/json
